/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/license-exchange/wrangler.live.jsonc --include-runtime=false workers/license-exchange/worker-configuration.d.ts` (hash: 3b55d465aa695d5e3ff1dcfc13f00998)
interface __BaseEnv_Env {
	PURCHASE_KEY_RATE_LIMITER: RateLimit;
	IP_RATE_LIMITER: RateLimit;
	LEMON_TEST_MODE: "false";
	LEMON_STORE_ID: string;
	LEMON_PRODUCT_ID: string;
	LEMON_VARIANT_ID: string;
	LEMON_API_KEY: string;
	AKC_ED25519_PRIVATE_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "LEMON_TEST_MODE" | "LEMON_STORE_ID" | "LEMON_PRODUCT_ID" | "LEMON_VARIANT_ID" | "LEMON_API_KEY" | "AKC_ED25519_PRIVATE_KEY">> {}
}
